name: midi2swift-ci
on:
  push:
  pull_request:
jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build tools
        run: swift build --package-path tools
      - name: Generate spec matrix
        run: .build/debug/MatrixBuilder --out spec/matrix.json --sources spec/sources/checksums.json
        working-directory: tools
      - name: Assert Full Spec (strict tests)
        run: STRICT_FULL_SPEC=1 swift test --package-path swift/Midi2Swift
      - name: Upload matrix.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spec-matrix
          path: spec/matrix.json
