name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # Select Xcode 16 (Swift 6)
      - name: Select Xcode 16 (Swift 6)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      - name: Show toolchain
        run: |
          xcodebuild -version
          swift --version

      - name: Build tools
        run: swift build -c debug
        working-directory: tools

      - name: Build matrix
        run: .build/debug/MatrixBuilder --in spec --out spec/matrix.json
        working-directory: tools

      - name: Codegen Swift sources
        run: .build/debug/SwiftGen --matrix spec/matrix.json --out swift/Midi2Swift/Sources
        working-directory: tools

      # PRs: non-strict verify, so feature PRs can go green while we add coverage
      - name: Verify (non-strict on PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: .build/debug/ContractVerifier --matrix spec/matrix.json --golden spec/golden --sources ../swift/Midi2Swift/Sources
        working-directory: tools

      # main: strict verify (enforce 100% on main)
      - name: Verify (STRICT on main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          STRICT_FULL_SPEC: '1'
        run: .build/debug/ContractVerifier --matrix spec/matrix.json --golden spec/golden --sources ../swift/Midi2Swift/Sources
        working-directory: tools

      - name: Build Swift package
        run: swift build
        working-directory: swift/Midi2Swift

      - name: Test
        run: swift test
        working-directory: swift/Midi2Swift
