name: Release notes (draft)

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
